### ISSUE TITLE
The Dream Tool !

### ISSUE THREAD

**Issue by suliveevil** [mg979/do.vim#1]
do.vim and vim-which-key complement each other !

**Comment by mg979** [comment]
How is it that they complement each other?

**Comment by suliveevil** [comment]
vim-which-key works only for Leader key.
My leader key is <kbd>Space</kbd>,
do.vim seems doesn't recognize Leader by `ShowDos <Leader>` or `ShowDos <Space>`

**Comment by mg979** [comment]
> do.vim seems doesn't recognize Leader by ShowDos <Leader> or ShowDos <Space>

It should work now

**Comment by suliveevil** [comment]
Thank hou very much.
